# Generated by Django 5.2.6 on 2025-09-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
