# Generated by Django 5.2.6 on 2025-09-06 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_courier_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='users.controller'),
        ),
    ]
