services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: courier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
